### ISSUE TITLE
Not supporting in corvus 16.0

### ISSUE THREAD

**Issue by Nani12-34** [redcliff-op/kernelR_xiaomi_phoenix#1]
Unable to boot on corvus 16.0

**Comment by redcliff-op** [comment]
![ok](https://user-images.githubusercontent.com/78088434/126692535-6df8ce95-b10b-4c3f-bdd9-6da01c3a46db.jpg)

Corvus needs appended dtb ( image.gz-dtb )
you can flash it in upcoming corvus builds but not for now
i clearly mentioned that in notes aswell
